name    'bjoernalbers-homebrew'
version '0.2.0'
summary 'A Homebrew package provider for Mac OS X (brewery included)'
description '(Please visit the project page!)'
project_page 'https://github.com/bjoernalbers/puppet-homebrew'
license 'Apache License, Version 2.0'
author 'bjoernalbers'
